version: '3.8'

services:
  react:
    build: .
    container_name: premium-spa
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true